In [1]:
import numpy
from numpy.linalg import eig, eigh, qr, det
from scipy.linalg import lu

In [2]:
n = 5
m = 2
K = numpy.random.randn(n, n)
K = K.T @ K
X = numpy.random.randn(n, m)
q, r = qr(X)
X = q
P = X @ X.T

In [3]:
def pr(a):
    numpy.set_printoptions(precision=3)
    print(a)

def _lu(a):
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                a[i,k] = lam
    return a

In [11]:
def _lu2(A):
    
    n = A.shape[0]
    L = numpy.eye(n)
    for k in range(n):
        # For each row k, access columns from k+1 to the end and divide by
        # the diagonal coefficient at A(k ,k)
        L[k+1:n, k] = A[k+1:n, k] / A[k, k];

        # For each row k+1 to the end, perform Gaussian elimination
        # In the end, A will contain U
        #for l in range(k+1, n):
        #    A[l, :] = A[l, :] - L[l, k] * A[k, :]
        #for l in range(k+1, n):
        A[k+1:, :] -= numpy.outer(L[k+1:, k], A[k, :])
       
    return L, A

def _chol(A):
    n = A.shape[0]
    L = numpy.zeros_like(A)
    for k in range(n):
        L[k, k] = numpy.sqrt(A[k, k])
        
        for j in range(k+1, n):
            L[j, k] = A[j, k] / L[k, k]
            
        for j in range(k + 1, n):
            for i in range(j, n):
                A[i, j] -= L[j, k] * L[i, k]
    return L

In [5]:
K2 = numpy.copy(K)
l, u = _lu2(K2)
pr(K - l@u)
pr(K)

[[ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  2.776e-17  0.000e+00  0.000e+00]
 [ 0.000e+00 -2.776e-17 -4.441e-16  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]]
[[ 4.985  1.155 -1.705 -3.636  0.803]
 [ 1.155  3.622  0.222 -0.575  1.615]
 [-1.705  0.222  3.955  2.569 -0.486]
 [-3.636 -0.575  2.569  4.116 -0.566]
 [ 0.803  1.615 -0.486 -0.566  2.732]]


In [18]:
K2 = numpy.copy(K)
l = _chol(K2)
pr(K - l@l.T)
pr(l)
pr(K2)

[[ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  4.441e-16  5.551e-17  0.000e+00 -2.220e-16]
 [ 0.000e+00  5.551e-17  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00 -2.220e-16  0.000e+00  0.000e+00  0.000e+00]]
[[ 2.233  0.     0.     0.     0.   ]
 [ 0.517  1.831  0.     0.     0.   ]
 [-0.764  0.337  1.805  0.     0.   ]
 [-1.629  0.146  0.707  0.971  0.   ]
 [ 0.36   0.78  -0.263  0.094  1.384]]
[[ 4.985  1.155 -1.705 -3.636  0.803]
 [ 1.155  3.354  0.222 -0.575  1.615]
 [-1.705  0.617  3.258  2.569 -0.486]
 [-3.636  0.268  1.276  0.942 -0.566]
 [ 0.803  1.429 -0.474  0.091  1.916]]
